### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by rhythm232** [Maripoforest/Smart-Light-Bulb-Control-with-Gesture#17]
add new object in window @rhythm232

**Comment by Maripoforest** [comment]
Please add framerate switch button, return a boolean, true for 8Hz, false for 1Hz

**Comment by rhythm232** [comment]
@Maripoforest  fixed  UI  for u

**Comment by Maripoforest** [comment]
Qt size not fit, try a compact layout plz @rhythm232
